<?php
$id=$_GET["uc"];
require('naisance.php');
$pdf = new naisance( 'P', 'mm', 'A4',true,'UTF-8',false );
$pdf->setPrintHeader(false);$pdf->SetAutoPageBreak(TRUE, 0);$pdf->setPrintFooter(false);
$pdf->AddPage('P','A4');
$pdf->mysqlconnect();
$query = "select * from naissance WHERE  id = '$id'    ";
$resultat=mysql_query($query);
while($result=mysql_fetch_object($resultat))
{
if ($result->MAC=='VB') {$voie='Normale';} else {$voie='Césarienne';} 
$pdf->SetFont('aefurat','B',13);
$pdf->SetFillColor(245);
$nec =$result->id;//ROUGE NOIR $pdf->SetTextColor(255,0,0);$pdf->SetTextColor(0,0,0);
$pdf->RoundedRect($x=4,  $y=4,   $w=202, $h=26, $r=2, $round_corner='1111', $style='', $border_style=array(), $fill_color=array());// $pdf->RoundedRect(4, 4, 202, 15, 2, $style = '');
$pdf->SetXY(5,5);$pdf->Cell(200,6,$pdf->repfr,0,1,'C');
$pdf->SetXY(5,$pdf->GetY());$pdf->Cell(200,6,$pdf->mspfr,0,1,'C');
$pdf->SetXY(5,$pdf->GetY());$pdf->Cell(200,6,$pdf->dspfr.$pdf->nbrtostring("wil","IDWIL",$pdf->nbrtostring("structure","id",$result->STRUCTURED,"idwil"),"WILAYAS"),0,1,'C');
$pdf->SetXY(5,$pdf->GetY());$pdf->Cell(200,6,"RÉSUMÉ STANDARD DE SORTIE",0,1,'C',1,0);
$pdf->SetFont('aefurat','B',10);
$pdf->RoundedRect($x=4,$y=30,$w=135,$h=22, $r=2,$round_corner='1111', $style='', $border_style=array(), $fill_color=array());// $pdf->RoundedRect(4, 20, 135, 25, 2, $style = '');
$pdf->RoundedRect($x=140,$y=30,$w=66,$h=39, $r=2,$round_corner='1111', $style='', $border_style=array(), $fill_color=array());// $pdf->RoundedRect(140, 20, 66, 40, 2, $style = '');
$pdf->SetXY(5,$pdf->GetY()+2.5);$pdf->Cell(133,5,"ETABLISSEMENT : ".$pdf->nbrtostring("structure","id",$result->STRUCTURED,"structure"),0,1,'L',1,0);$pdf->SetXY(141,$pdf->GetY()-5);$pdf->Cell(64,5,"RESERVE AU BUREAU DES",0,1,'C',1,0);
$pdf->SetXY(5,$pdf->GetY()+1);$pdf->Cell(133,5,"SERVICE DE : ".$pdf->nbrtostring("servicedeces","id",$result->SERVI,"service"),0,1,'L',1,0);  $pdf->SetXY(141,$pdf->GetY()-5);$pdf->Cell(64,5,"ENTREES",0,1,'C',1,0);
$pdf->SetXY(5,$pdf->GetY()+1);$pdf->Cell(133,5,"CHEF DE SERVICE : *** ",0,1,'L',1,0);           $pdf->SetXY(141,$pdf->GetY()+5);$pdf->Cell(64,5,"CODE SERVICE",0,1,'C',1,0);
                                                                                                $pdf->SetXY(141,$pdf->GetY()+1);$pdf->Cell(64,5,"_________________________________",0,1,'C',1,0);
$pdf->SetFont('aefurat','B',10);
$pdf->RoundedRect($x=4,  $y=52,   $w=135, $h=46, $r=2, $round_corner='1111', $style='', $border_style=array(), $fill_color=array());// $pdf->RoundedRect(4, 45, 135, 46, 2, $style = '');
$pdf->RoundedRect($x=6,  $y=54,   $w=64,  $h=15, $r=2, $round_corner='1111', $style='', $border_style=array(), $fill_color=array());// $pdf->RoundedRect(6, 47, 64, 15, 2, $style = '');                     
$pdf->RoundedRect($x=73, $y=54,   $w=64,  $h=15, $r=2, $round_corner='1111', $style='', $border_style=array(), $fill_color=array());// $pdf->RoundedRect(73, 47, 64, 15, 2, $style = '');
$pdf->Text(10,56,"MATRICULE : ".$result->MATRI);                              $pdf->Text(76,56,"N° DOSSIER DANS SERVICE : ".$result->NDOSS);                 
$pdf->Text(5,71,"NOM   ET  PRENOM : ".$result->NOM3.'_'.$result->PRENOM2);    $pdf->Text(100,71,"SEXE : FEMININ ");   
$pdf->Text(5,76,"DATE DE NAISSANCE : ".$pdf->dateUS2FR($result->DATENS2));    $pdf->Text(100,76,"AGE : ".$result->AGE2);  
$pdf->Text(5,81,"COMMUNE DE NAISSANCE : ".$pdf->nbrtostring("com","IDCOM",$result->COMMUNE2,"COMMUNE")); 
$pdf->Text(5,86,"WILAYAS DE RESIDENCE : ".$pdf->nbrtostring("wil","IDWIL",$result->WILAYA4,"WILAYAS"));  
$pdf->Text(5,91,"DATE D'ADMISSION A L'HOPITAL : ".$pdf->dateUS2FR($result->HOSPI));
$pdf->RoundedRect($x=4,  $y=98,   $w=135, $h=10, $r=2, $round_corner='1111', $style='', $border_style=array(), $fill_color=array());// $pdf->RoundedRect(4, 91, 135, 10, 2, $style = '');
$pdf->Text(35,101," DERNIER SERVICE  D'HOSPITALISATION");
$pdf->RoundedRect($x=4,  $y=108,   $w=135, $h=40, $r=2, $round_corner='1111', $style='', $border_style=array(), $fill_color=array());// $pdf->roundedrect(4, 101, 135, 40, 2, $style = '');
$pdf->Text(5,110,"DATE D'ENTREE AU SERVICE : ".$pdf->dateUS2FR($result->HOSPI));
$pdf->Text(5,120,"MEDECIN TRAITANT : ");
$pdf->Text(5,130,"MODE DE SORTIE : ".$pdf->nbrtostring("modesrt","id",$result->MSORT,"mods"));
$pdf->Text(5,140,"DATE DE SORTIE DE L'HOPITAL : ".$pdf->dateUS2FR($result->SORT));
$pdf->RoundedRect($x=4,  $y=148,   $w=135, $h=100, $r=2, $round_corner='1111', $style='', $border_style=array(), $fill_color=array());// $pdf->RoundedRect(4, 141, 135, 100, 2, $style = '');
$pdf->Text(5,150,"MOTIF D'HOSPITALISATION : ".$result->MOTIF );
$pdf->Text(5,160,"__________________________________________________________________________");
$pdf->Text(5,170,"DIAGNOSTIC PRINCIPAL DE SORTIE : ".$result->DGCNS.' '.$voie );
$pdf->Text(5,180,"__________________________________________________________________________");
$pdf->Text(50,190,"DIAGNOSTICS ASSOCIES ");
$pdf->Text(5,200,"1- ________________________________________________________________________");
$pdf->Text(5,210,"2- ________________________________________________________________________");
$pdf->Text(5,220,"3- ________________________________________________________________________");
$pdf->Text(5,252,"Chef de service : ");$pdf->Text(150,252,"Médecin traitant : ");
$pdf->RoundedRect($x=140,$y=52+17,   $w=66,  $h=179, $r=2, $round_corner='1111', $style='', $border_style=array(), $fill_color=array());
$pdf->Text(142,73,"CODE COMMUNE DE NAISSANCE :");   $pdf->Text(142,73+5,"_________________________________");
$pdf->Text(142,73+10,"CODE WILAYA DE RESIDENCE : ");$pdf->Text(142,73+15,"_________________________________");
$pdf->Text(142,110,"MATRICULE DU PRATICIEN:");      $pdf->Text(142,110+5,"_________________________________");
$pdf->Text(142,110+10,"CODE MODE DE SORTIE :");     $pdf->Text(142,110+15,"_________________________________");
$pdf->Text(141,170,"CIM-10 :__________________________");
$pdf->Text(141,200,"CIM-10 :__________________________");
$pdf->Text(141,210,"CIM-10 :__________________________");
$pdf->Text(141,220,"CIM-10 :__________________________");
$pdf->SetFont('aefurat','B',8);
$pdf->Text(5,290,"REF : INSTRUCTION N° 17 /MSPRH/MIN 2002 DU 24 OCT 2002 : destiné essentiellement au recueil de l'information épidémiologique hospitalière en 02 exemplaires ");
$pdf->AddPage('p','A4');
$pdf->SetFont('aefurat','B',13);
$pdf->RoundedRect($x=4,  $y=4,   $w=202, $h=26, $r=2, $round_corner='1111', $style='', $border_style=array(), $fill_color=array());// $pdf->RoundedRect(4, 4, 202, 15, 2, $style = '');
$pdf->SetXY(5,5);$pdf->Cell(200,6,$pdf->repfr,0,1,'C');
$pdf->SetXY(5,$pdf->GetY());$pdf->Cell(200,6,$pdf->mspfr,0,1,'C');
$pdf->SetXY(5,$pdf->GetY());$pdf->Cell(200,6,$pdf->dspfr.$pdf->nbrtostring("wil","IDWIL",$pdf->nbrtostring("structure","id",$result->STRUCTURED,"idwil"),"WILAYAS"),0,1,'C');
$pdf->SetXY(5,$pdf->GetY());$pdf->Cell(200,6,"RÉSUMÉ CLINIQUE DE SORTIE",0,1,'C',1,0);
$pdf->SetFont('aefurat','B',10);
$pdf->RoundedRect($x=4,$y=30,$w=135,$h=22, $r=2,$round_corner='1111', $style='', $border_style=array(), $fill_color=array());
$pdf->RoundedRect($x=140,$y=30,$w=66,$h=22, $r=2,$round_corner='1111', $style='', $border_style=array(), $fill_color=array());
$pdf->SetXY(5,$pdf->GetY()+2.5);$pdf->Cell(133,5,"ETABLISSEMENT : ".$pdf->nbrtostring("structure","id",$result->STRUCTURED,"structure"),0,1,'L',1,0);$pdf->SetXY(141,$pdf->GetY()-5);$pdf->Cell(64,5,"MATRICULE : ".$result->MATRI,0,1,'L',1,0);
$pdf->SetXY(5,$pdf->GetY()+1);$pdf->Cell(133,5,"SERVICE DE : GYNECO-OBSTETRIQUE ",0,1,'L',1,0);                     
$pdf->SetXY(5,$pdf->GetY()+1);$pdf->Cell(133,5,"CHEF DE SERVICE : *** ",0,1,'L',1,0);          $pdf->SetXY(141,$pdf->GetY()-5);$pdf->Cell(64,5,"N° DOSSIER : ".$result->NDOSS,0,1,'L',1,0);
                                                                                               $pdf->RoundedRect($x=4,  $y=52,   $w=202, $h=40, $r=2, $round_corner='1111', $style='', $border_style=array(), $fill_color=array());
$pdf->Text(5,25+30,"NOM : ".$result->NOM3);  $pdf->Text(50,25+30,"PRENOM : ".$result->PRENOM2);$pdf->Text(115,25+30,"DATE DE NAISSANCE : ".$pdf->dateUS2FR($result->DATENS2));$pdf->Text(175,25+30,"SEXE : FEMININ ");
$pdf->Text(5,35+30,"COMMUNE DE NAISSANCE : ".$pdf->nbrtostring("com","IDCOM",$result->COMMUNE2,"COMMUNE"));$pdf->Text(115,35+30,"WILAYA DE NAISSANCE : ".$pdf->nbrtostring("wil","IDWIL",$result->WILAYA2,"WILAYAS"));
$pdf->Text(5,45+30,"DATE D'HOSPITALISATION : ".$pdf->dateUS2FR($result->HOSPI));$pdf->Text(115,45+30,"MODE D'ENTREE : ".$pdf->nbrtostring("modeent","id",$result->MODEE,"mods"));
$pdf->Text(5,55+30,"SERVICE : ".$pdf->nbrtostring("servicedeces","id",$result->SERVI,"service")); $pdf->Text(70,55+30,"DATE D'ENTREE AU SERVICE : ".$pdf->dateUS2FR($result->HOSPI));$pdf->Text(141,55+30,"DATE SORTI DU SERVICE : ".$pdf->dateUS2FR($result->SORT));
$pdf->SetFont('aefurat','B',12);
$pdf->RoundedRect($x=4,  $y=92,   $w=202, $h=180, $r=2, $round_corner='1111', $style='', $border_style=array(), $fill_color=array());
$pdf->Text(5,92,"MOTIF D'HOSPITALISATION : Accouchement");
$pdf->Text(5,102,"............................................................................................................................................................................................");
$pdf->Text(5,95+20,"BILAN BIOLOGIQUE : ");$pdf->Line(4 ,95+20,206 ,95+20 );

$pdf->Text(5,115+9,"FNS GROUPAGE RH ");
$pdf->Text(5,115+9,"");
$pdf->Text(5,115+10,"............................................................................................................................................................................................");
$pdf->Text(5,115+20,"............................................................................................................................................................................................");
$pdf->Text(5,129+20,"BILAN RADIOLOGIQUE :");$pdf->Line(4 ,129+20,206 ,129+20); 
$pdf->Text(5,128+30,"ECHOGRAPHIE OBSTERICAL");
$pdf->Text(5,128+40,"");
$pdf->Text(5,129+30,"............................................................................................................................................................................................");
$pdf->Text(5,129+40,"............................................................................................................................................................................................");



$pdf->Text(5,162+20,"AUTRES EXAMENS :");$pdf->Line(4 ,162+20,206 ,162+20 );
$pdf->Text(5,162+30,"............................................................................................................................................................................................");
$pdf->Text(5,185+20,"DIAGNOSTIC PRINCIPAL DE SORTIE : Accouchement ".$voie );$pdf->Line(4 ,185+20,206 ,185+20 );
$pdf->Text(5,185+30,"............................................................................................................................................................................................");
$pdf->Text(5,195+25,"DIAGNOSTICS ASSOCIES"); 
$pdf->Text(5,200+25+2,"DA1 :.................................................................................................................................................................................");
$pdf->Text(5,205+25+2,"DA2 :.................................................................................................................................................................................");
$pdf->Text(5,210+25+2,"DA2 :.................................................................................................................................................................................");
$pdf->Text(5,215+30,"ACTES ET TRAITEMENTS : Accouchement");
$pdf->Text(5,215+40,"............................................................................................................................................................................................");
$pdf->SetFont('aefurat','B',10);
$pdf->Text(5,250+30,"Chef de service : ");
$pdf->Text(150,250+30,"Medecin traitant : ");
$pdf->SetFont('aefurat','B',9);
$pdf->Text(5,290,"REF : INSTRUCTION N° 17 /MSPRH/MIN 2002 DU 24 OCT 2002 : la remise est systématique à tout patient hospitalisé sortant");
}
$pdf->Output();
?>